// <auto-generated />
using System;
using BlissRecruitment.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlissRecruitment.Migrations
{
    [DbContext(typeof(BlissRecruitmentDBContext))]
    [Migration("20181209184804_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlissRecruitment.Models.ChoiceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Choice");

                    b.Property<int?>("QuestionEntityId");

                    b.Property<int>("Votes");

                    b.HasKey("Id");

                    b.HasIndex("QuestionEntityId");

                    b.ToTable("Choices");
                });

            modelBuilder.Entity("BlissRecruitment.Models.QuestionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl");

                    b.Property<DateTime>("Published");

                    b.Property<string>("Question");

                    b.Property<string>("ThumbUrl");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("BlissRecruitment.Models.ChoiceEntity", b =>
                {
                    b.HasOne("BlissRecruitment.Models.QuestionEntity")
                        .WithMany("Choices")
                        .HasForeignKey("QuestionEntityId");
                });
#pragma warning restore 612, 618
        }
    }
}
